#+TITLE: StumpWM Config
#+AUTHOR: Luca Andriotto
#+PROPERTY: header-args :tangle config
#+auto_tangle: t
#+DESCRIPTION: Il window manager che sto iniziando ad apprezzare.
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Table of Contents :toc:
- [[#initializations][INITIALIZATIONS]]
  - [[#groups][Groups]]
  - [[#variables][Variables]]
  - [[#modularity][Modularity]]
  - [[#system-helpers][System Helpers]]
  - [[#files][Files]]
  - [[#modules][Modules]]
  - [[#keymaps][Keymaps]]
  - [[#runners][Runners]]
  - [[#themes][Themes]]
- [[#appeareance][APPEAREANCE]]
  - [[#parameters][Parameters]]
  - [[#borders][Borders]]
  - [[#desktop-background][Desktop background]]
  - [[#fonts][Fonts]]
  - [[#gaps][Gaps]]
  - [[#messageinput-box][Message/Input box]]
  - [[#startup-message][Startup message]]
  - [[#which-key][Which-key]]
- [[#keybindings][KEYBINDINGS]]
  - [[#applications][Applications]]
  - [[#backlight][Backlight]]
  - [[#buffers][Buffers]]
  - [[#layout][Layout]]
  - [[#movement][Movement]]
  - [[#search][Search]]
  - [[#system][System]]
  - [[#volume][Volume]]
- [[#settings][SETTINGS]]
  - [[#prefix-key][Prefix key]]
  - [[#completion][Completion]]
  - [[#input-devices][Input Devices]]
  - [[#messageinput-box-1][Message/Input box]]
  - [[#modeline][Modeline]]
  - [[#session][Session]]
  - [[#startup][Startup]]
  - [[#windows][Windows]]

* TODO INITIALIZATIONS
** Groups
#+begin_src lisp
  (in-package :stumpwm)

  ;; creating groups
  (setf *group-web*   "^f1    ^f0")
  (setf *group-dev*   "^f1    ^f0")
  (setf *group-read*  "^f1    ^f0")
  (setf *group-relax* "^f1    ^f0")

  ;; web
  (setf (group-name (first (screen-groups (current-screen)))) *group-web*)
  ;; dev
  (gnewbg *group-dev*)
  ;; read
  (gnewbg *group-read*)
  ;; relax
  (gnewbg *group-relax*)

  (setf *group-format* "%t")
#+end_src

** Variables
*** Directories
#+begin_src lisp
  (defvar al/init-directory
    (directory-namestring
     (truename (merge-pathnames
                "stumpwm" (uiop:xdg-config-pathname))))
    "A directory with initially loaded files.")

  (defvar al/modules-directory
    (directory-namestring
     (truename (merge-pathnames
                ".stumpwm.d/modules" (user-homedir-pathname))))
    "A directory with initially loaded files.")

  (defvar al/data-directory
    (directory-namestring
     (truename (merge-pathnames
                (uiop:xdg-data-pathname) "stumpwm")))
    "A directory with data files.")
#+end_src

*** Logs
#+begin_src lisp
  (redirect-all-output (merge-pathnames "log" al/data-directory))
#+end_src

** Modularity
#+begin_src lisp
  (defun al/load (filename)
    "Load a file FILENAME (without extension) from `al/init-directory'."
    (let ((file (merge-pathnames (concat filename ".lisp")
                                 al/init-directory)))
      (if (probe-file file)
          (load file)
          (format *error-output* "File '~a' doesn't exist." file))))

  (defun al/load-module (name)
    "Load contributed stumpwm module NAME.
  Return nil, if the module does not exist.
  This function is similar to `load-module' command, except it returns nil
  instead of any error."
    (let ((module (find-module (string-downcase name))))
      (and module
           (progn (asdf:operate 'asdf:load-op module)
                  t))))
#+end_src

** System Helpers
*** Battery
#+begin_src lisp
  (defparameter *battery-percent* "")

  (defun get-battery-status ()
    (let* ((batgetcap (run-shell-command "cat /sys/class/power_supply/BAT0/capacity | tr -d '\\r\\n'" t)))
      (setf *battery-percent* (format nil "^6^f1^f0^n ~a% " batgetcap))))

  (defun battery-percentage (ml)
    (declare (ignore ml))
    ,*battery-percent*)

  (run-with-timer 0 10 #'get-battery-status)
  (add-screen-mode-line-formatter #\B #'battery-percentage)
#+end_src

*** Date
Managed by =*time-modeline-string*=

*** Colon
#+begin_src lisp
  ;; prompt the user for an interactive command. The first arg is an
  ;; optional initial contents.
  (defcommand colon1 (&optional (initial "")) (:rest)
    (let ((cmd (read-one-line (current-screen) ": " :initial-input initial)))
      (when cmd
        (eval-command cmd t))))
#+end_src

*** Keybindings
#+begin_src lisp
  (defun tr-define-key (key command)
    (define-key *top-map* (kbd (concat "s-" key )) command)
    (define-key *root-map* (kbd key) command))
#+end_src

*** Search
#+begin_src lisp
;; Web jump (works for DuckDuckGo and Imdb)
(defmacro make-web-jump (name prefix)
  `(defcommand ,(intern name) (search) ((:rest ,(concatenate 'string name " search: ")))
    (nsubstitute #\+ #\Space search)
    (run-shell-command (concatenate 'string ,prefix search))))
#+end_src

*** Splitting
Focus the created frame.
#+begin_src lisp
  (defcommand al/hsplit () ()
    (hsplit)
    (move-focus :right))

  (defcommand al/vsplit () ()
    (vsplit)
    (move-focus :down))
#+end_src

*** Syncthing
#+begin_src lisp
  (defvar *syncthing-p* nil
    "Keeps track of Syncthing execution, off by default on startup")

  (defcommand start-syncthing () ()
    "Launch Syncthing if it is not already running"
    (if *syncthing-p*
        (message "Syncthing is already running")
        (progn
          (run-shell-command "syncthing --no-browser &")
          (setf *syncthing-p* t)
          (message "Launching ^6Syncthing^n..."))))

  (defcommand stop-syncthing () ()
    "Stop Syncthing"
    (stumpwm:run-shell-command "killall syncthing")
    (setf *syncthing-p* nil)
    (message "^6Syncthing^n is now stopped."))

  (defcommand toggle-syncthing () ()
    (if *syncthing-p*
        (run-commands "stop-syncthing")
        (run-commands "start-syncthing")))

  ;; modeline status

  (defun get-syncthing-status ()
    (if *syncthing-p*
        (setf *syncthing-ml-status*
              (format nil "^6^f1^f0^n "))
        (setf *syncthing-ml-status* "")))

  (defun ml-fmt-syncthing-status (ml)
    (declare (ignore ml))
    (get-syncthing-status))

  (add-screen-mode-line-formatter #\s #'ml-fmt-syncthing-status)
#+end_src

** Files
#+begin_src lisp
  (al/load "keymaps")
  (al/load "modules")
  (al/load "themes")
#+end_src

** TODO Modules
See [[file:modules.org][Modules]].

** Keymaps
Keymaps to handle modules.
See [[file:keymaps.org][Keymaps]].

** Runners
This section gathers all the program wrappers.
#+begin_src lisp
  ;; Editor
  (defcommand editor () ()
    "run emacs"
    (run-or-raise "emacsclient -c" '(:class "Emacs")))
  ;; Browsers
  (defcommand browser () ()
    "run firefox"
    (run-or-raise "firefox" '(:class "firefox")))
  (defcommand nyxt () ()
    "run nyxt"
    (run-or-raise "nyxt" '(:class "Nyxt")))
  (defcommand brave () ()
    "run brave"
    (run-or-raise "brave" '(:class "Brave")))
  ;; News
  (defcommand newsboat () ()
    "run `newsboat`"
    (run-or-raise "alacritty -T 'newsboat' -e 'newsboat'" '(:title "newsboat")))
  ;; Office
  (defcommand libreoffice () ()
    "run LibreOffice"
    (run-or-raise "libreoffice7.6" '(:class "LibreOffice")))
  ;; Engineering
  (defcommand matlab () ()
    (run-or-raise "/usr/local/MATLAB/R2023a/bin/matlab" '(:class "MATLAB")))
  ;; Study and research
  (defcommand sioyek () ()
    "run `sioyek`"
    (run-or-raise "sioyek" '(:class "sioyek")))
#+end_src

** TODO Themes
See [[file:themes.org][Themes]].

* TODO APPEAREANCE
Changing themes for the various graphical components. Fare il merge con theme fuori.
** Parameters
#+begin_src lisp
  ;; Input box
  (defparameter *msg-bg-color*     (nth 0 *colors*))
  (defparameter *msg-fg-color*     (nth 8 *colors*))
  (defparameter *msg-border-color* (nth 5 *colors*))
  ;; Mode-line
  (defparameter *mode-line-bg-color* (nth 0 *colors*))
  (defparameter *mode-line-fg-color* (nth 8 *colors*))
#+end_src

** Borders
#+begin_src lisp
  (set-focus-color         *msg-border-color*)
  (set-win-bg-color        *msg-bg-color*)
  (set-unfocus-color       *msg-bg-color*)
  (set-float-focus-color   *msg-border-color*)
  (set-float-unfocus-color *msg-bg-color*)
#+end_src

** Desktop background
Simply putting a color for a background. It is possible to tweak it differently.
#+begin_src lisp
  ;; set desktop background color
  (setf (xlib:window-background (screen-root (current-screen))) #x47456d)
#+end_src

** TODO Fonts
Muovi in Themes, mantieni l'entry creando il collegamento. Usare qualche simbolo nella modeline.
#+begin_src lisp
  (set-font (list
             (make-instance 'xft:font
                            :family "Hack"
                            :subfamily "Bold"
                            :size 13)
             (make-instance 'xft:font
                            :family "FontAwesome"
                            :subfamily "Regular"
                            :size 14)))
  (xft:cache-fonts)
#+end_src

** Gaps
Allowing gaps for better aesthetics.
#+begin_src lisp
  ;; Head gaps run along the 4 borders of the monitor(s)
  (setf swm-gaps:*head-gaps-size* 0        ;; Head gaps run along the 4 borders of the monitor(s)
        swm-gaps:*inner-gaps-size* 13      ;; Inner gaps run along all the 4 borders of a window
        swm-gaps:*outer-gaps-size* 7)      ;; Outer gaps add more padding to the outermost borders of a window (touching
  ;; the screen border)

  (swm-gaps:toggle-gaps)
#+end_src

** Message/Input box
#+begin_src lisp
  ;; message/input bar colors
  (set-bg-color     *msg-bg-color*)
  (set-fg-color     *msg-fg-color*)
  (set-border-color *msg-border-color*)
#+end_src

** Startup message
#+begin_src lisp
  ;; startup message
  (setf *startup-message* "^6    Stump Window Manager ^8has initialized!
    Press ^6Ctrl+t ? ^8for Help. ^6Never Stop Hacking!^n
              Powered with ^87 Common Lisp ")
#+end_src

** Which-key
#+begin_src lisp
  ;; (setf *key-seq-color* "^3")
  ;; (setf *which-key-format* "~3a -> ~a")
#+end_src

* KEYBINDINGS
Listed alphabetically (with respect to the keybinding). I would like to create a map or a menu for pomodoro timer.
** Applications
#+begin_src lisp
  ;; audio
  (define-key *root-map* (kbd "a") "exec alacritty -e alsamixer")
  ;; alert me
  (define-key *top-map* (kbd "s-a") "alert-me-at")
  ;; browser
  (define-key *root-map* (kbd "b") "browser")
  ;; terminal
  (define-key *root-map* (kbd "c") "exec alacritty")
  ;; launcher
  ;; (define-key *root-map* (kbd "d") "exec dmenu_run -l 10 -p 'What program?' -fn 'Hack' -nb '#0d0e1c' -nf '#ffffff' -sb '#4a4f69'")
  (define-key *root-map* (kbd "d") "exec stumpwm-dmenu_run")
  ;; text editor
  (define-key *root-map* (kbd "e") "editor")
  ;; file manager (graphical)
  (define-key *root-map* (kbd "f") "exec pcmanfm")
  ;; file manager
  (define-key *root-map* (kbd "F") "exec alacritty -e lf")
  ;; g *GROUP-MAP* don't touch
  ;; h *HELP-MAP*  don't touch
  ;; i sioyek
  (define-key *root-map* (kbd "i") "sioyek")
  ;; j todo
  ;; k DELETE-WINDOW don't touch
  ;; l fix?
  (define-key *root-map* (kbd "l") "show-menu")
  ;; m lastmsg don't touch
  ;; n pull-hidden-next don't touch
  (define-key *root-map* (kbd "n") "newsboat")
  ;; o fnext don't touch
  ;; p pull-hidden-previous don't touch
  ;; P
  ;; s-p
  (define-key *top-map* (kbd "s-p") '*al/pomodoro-bindings*)
  ;; q quit-confirm don't touch
  ;; r iresize don't touch
  ;; R don't touch
  ;; s vsplit
  ;; s-s slynk
  ;; S hsplit
  ;; s-S syncthing
  (define-key *top-map* (kbd "s-S") "toggle-syncthing")
  ;; t don't touch
  ;; u todo
  ;; v todo
  ;; w todo
  ;; x *EXCHANGE-WINDOW-MAP* don't touch
  ;; y todo
  ;; z todo
  (define-key *root-map* (kbd "RET") "exec alacritty")
#+end_src

** Backlight
Controlling brightness.
#+begin_src lisp
  (define-key *root-map* (kbd "XF86MonBrightnessUp") "backlight-increase")
  (define-key *root-map* (kbd "XF86MonBrightnessDown") "backlight-decrease")
#+end_src

** Buffers
Handling hidden buffers behind frames.

#+begin_src lisp
  (define-key *top-map* (kbd "s-N") "pull-hidden-next")
  (define-key *top-map* (kbd "s-P") "pull-hidden-previous")
  (define-key *top-map* (kbd "s-S-SPC") "pull-hidden-next")
#+end_src

** Layout
#+begin_src lisp
  ;; Splitting
  (define-key *top-map* (kbd "s-s") "al/vsplit")
  (define-key *top-map* (kbd "s-h") "al/hsplit")

  (define-key *top-map* (kbd "s-r") "remove")
  (define-key *top-map* (kbd "s-R") "iresize")

  (define-key *top-map* (kbd "s-q") "only")

  ;; Resizing
  (define-key *top-map* (kbd "s-z") "iresize")

  ;; keyboard layout
  (define-key *top-map* (kbd "s-SPC") "switch-keyboard-layout")
#+end_src

** Movement
*** Groups
Handling jumping from one group to another with or without windows.

#+begin_src lisp
  (define-key *top-map* (kbd "s-`") "grouplist")

  (define-key *top-map* (kbd "s-C-n") "gselect 1")
  (define-key *top-map* (kbd "s-C-e") "gselect 2")
  (define-key *top-map* (kbd "s-C-o") "gselect 3")
  (define-key *top-map* (kbd "s-C-i") "gselect 4")

  (define-key *top-map* (kbd "s-C-N") "gmove-and-follow 1")
  (define-key *top-map* (kbd "s-C-E") "gmove-and-follow 2")
  (define-key *top-map* (kbd "s-C-O") "gmove-and-follow 3")
  (define-key *top-map* (kbd "s-C-I") "gmove-and-follow 4")
#+end_src

*** Windows
Shifting focus on windows being on different frames and moving them
around.

#+begin_src lisp
  (define-key *top-map* (kbd "s-x") '*al/exchange-window-map*)

  (define-key *top-map* (kbd "s-n") "move-focus left")
  (define-key *top-map* (kbd "s-e") "move-focus down")
  (define-key *top-map* (kbd "s-o") "move-focus up")
  (define-key *top-map* (kbd "s-i") "move-focus right")

  (define-key *top-map* (kbd "s-N") "move-window left")
  (define-key *top-map* (kbd "s-E") "move-window down")
  (define-key *top-map* (kbd "s-O") "move-window up")
  (define-key *top-map* (kbd "s-I") "move-window right")
#+end_src
** Search
Managing the interfaces to different sources for information research.
#+begin_src lisp
;; Various search
(make-web-jump "archlinux"  "firefox https://wiki.archlinux.org/title/")
(make-web-jump "duckduckgo" "firefox https://duckduckgo.com/?q=")
(make-web-jump "libgen"     "firefox http://libgen.li/index.php?req=")
(make-web-jump "wikipedia"  "firefox http://www.wikipedia.org/wiki/")

;; C-t M-s is a terrble binding, but you get the idea.
;; Browse somewhere
(define-key *root-map* (kbd "M-a") "archlinux")
(define-key *root-map* (kbd "M-b") "colon1 exec firefox http://www.")
(define-key *root-map* (kbd "M-s") "duckduckgo")
(define-key *root-map* (kbd "M-S") "libgen")
;; Browse somewhere
(define-key *root-map* (kbd "M-u") "colon1 exec firefox http://www.")
(define-key *root-map* (kbd "M-w") "wikipedia")
#+end_src
** System
Keybindings for managing system.
#+begin_src lisp
  ;; C-a todo
  ;; C-b banish don't touch
  (define-key *top-map* (kbd "s-b") "mode-line")
  ;; C-c todo
  ;; C-d todo
  ;; C-e todo
  ;;(define-key *top-map* (kbd "s-e") "gnext-with-window")
  ;; Fullscreen
  (define-key *root-map* (kbd "C-f") "fullscreen")
  (define-key *top-map* (kbd "s-f") "fullscreen")
  ;; C-g don't touch
  (define-key *top-map* (kbd "s-g") "al/toggle-golden-ratio")
  ;; C-h don't touch
  ;; C-i todo
  ;;(define-key *top-map* (kbd "s-i") "gnext")
  ;; C-j todo
  ;; C-k don't touch (fix?)
  ;; Lock screen
  (define-key *root-map* (kbd "C-l") "exec slock")
  ;; C-m fix, todo
  ;; C-n don't touch
  ;;(define-key *top-map* (kbd "s-n") "gprev")
  ;; Cycling groups
  (define-key *root-map* (kbd "C-o") "gnext")
  (define-key *root-map* (kbd "C-O") "gnext-with-window")
  ;;(define-key *top-map* (kbd "s-o") "gprev-with-window")
  ;; C-p don't touch
  ;; C-q todo
  (define-key *root-map* (kbd "C-q") "logout")
  ;; C-r todo
  (define-key *root-map* (kbd "C-r") "restart-computer")
  ;; C-s
  (define-key *root-map* (kbd "C-s") "shutdown-computer")
  (define-key *top-map* (kbd "s-l") "toggle-slynk")
  ;; C-t don't touch
  ;; C-u
  ;; C-v
  ;; C-w
  ;; C-x
  ;; C-y
  ;; C-z
  ;; .
#+end_src
** Volume
#+begin_src lisp
  (define-key *top-map* (kbd "XF86AudioRaiseVolume") "amixer-master-1+")
  (define-key *top-map* (kbd "XF86AudioLowerVolume") "amixer-master-1-")
  (define-key *top-map* (kbd "XF86AudioMute")        "amixer-master-toggle")
#+end_src

* SETTINGS
** Prefix key
This is the prefix key i normally use.
#+begin_src lisp
  (set-prefix-key (kbd "C-t"))
#+end_src

** Completion
#+begin_src lisp
  (setf *input-completion-show-empty* t)
  #+end_src

** Input Devices
*** Keyboard
#+begin_src lisp
  ;; Set keyboard layout
  (setf kbd-layouts:*caps-lock-behavior* :swapped)
  (kbd-layouts:keyboard-layout-list "us -variant workman" "it")
#+end_src
*** Mouse (Trackpad)
#+begin_src lisp
  ;; Focus Follow Mouse
  (setf *mouse-focus-policy* :click)
  ;; bugfix for scrolling doesn't work with an external mouse in GTK+3 Apps
  (setf (getenv "GDK_CORE_DEVICE_EVENTS") "1")
  ;; mouse pointer
  (run-shell-command "xsetroot -cursor_name left_ptr")
#+end_src

** Message/Input box
#+begin_src lisp
  (update-color-map (current-screen))
  ;; message timeout
  (setf *timeout-wait* 3)
#+end_src

** TODO Modeline
Sistemare pomodoro timer.

#+begin_src lisp
  (setf *mode-line-background-color*  *mode-line-bg-color* ; background
        ,*mode-line-foreground-color* *mode-line-fg-color* ; foreground
        ,*mode-line-border-color*     *mode-line-bg-color* ; border
        ,*time-modeline-string*       "^6^f1^f0^n %A, %e %B ^6^f1^f0^n %H:%M" ; time format string
        ,*mode-line-timeout*          5                    ; timeout (mode-line refresh)
        ,*mode-line-border-width*     3                    ; border width
        ,*mode-line-pad-x*            3                    ; text padding in x
        ,*mode-line-pad-y*            3)                   ; text padding in y

  ;; Ordine di comparsa
  (setf *screen-mode-line-format*
        (list "^6[%g]^n "       ; groups
              ;; "^5%t^n "         ; notifications
              "%W"              ; windows
              "^>"              ; right align
              "%S"              ; slynk status
              "%s"              ; syncthing status
              "%B"              ; battery percentage
              "%T"
              "%d"))            ; time/date

  ;; turn on the mode line
  (if (not (head-mode-line (current-head)))
      (toggle-mode-line (current-screen) (current-head)))
#+end_src
*** Formatters
(#\A EMPTY)
(#\a EMPTY)
(#\B #<FUNCTION BATTERY-PERCENTAGE>)
(#\C EMPTY)
(#\c EMPTY)
(#\D EMPTY)
(#\d FMT-MODELINE-TIME)
(#\E STUMPWM-WEATHER::MODE-LINE-STR)
(#\e EMPTY)
(#\F EMPTY)
(#\f EMPTY)
(#\G EMPTY)
(#\g FMT-GROUP-LIST)
(#\H EMPTY)
(#\h FMT-HEAD)
(#\I #<FUNCTION WIFI::FMT-WIFI>)
(#\i EMPTY)
(#\J EMPTY)
(#\j EMPTY)
(#\K EMPTY)
(#\k EMPTY)
(#\L #<FUNCTION KBD-LAYOUTS::CURRENT-KEYBOARD-LAYOUT>)
(#\l EMPTY)
(#\M FMT-ALL-MINOR-MODES)
(#\m FMT-MINOR-MODES)
(#\N NOTIFICATIONS::NOTIFICATIONS-AS-STRING)
(#\n FMT-GROUP)
(#\O EMPTY)
(#\o EMPTY)
(#\P EMPTY)
(#\p EMPTY)
(#\Q EMPTY)
(#\q EMPTY)
(#\R EMPTY)
(#\r EMPTY)
(#\S #<FUNCTION ML-FMT-SLYNK-STATUS>)
(#\s #<FUNCTION ML-FMT-SYNCTHING-STATUS>)
(#\T ?)
(#\t TOMATO:MODELINE)
(#\U EMPTY)
(#\u FMT-URGENT-WINDOW-LIST)
(#\V EMPTY)
(#\v FMT-HEAD-WINDOW-LIST-HIDDEN-WINDOWS)
(#\W FMT-HEAD-WINDOW-LIST)
(#\w FMT-WINDOW-LIST)
(#\X EMPTY)
(#\x EMPTY)
(#\Y EMPTY)
(#\y EMPTY)
(#\Z EMPTY)
(#\z EMPTY)

** Session
#+begin_src lisp
  ;; set DESKTOP_SESSION variable
  (setf (getenv "DESKTOP_SESSION") "stumpwm")
#+end_src

** Startup
#+begin_src emacs-lisp
  (start-syncthing)
#+end_src

** Windows
*** Borders
#+begin_src lisp
  (setf 
   ;; format
   ,*window-format*                       "%m%s%20t"
   ;; gravities
   ,*message-window-gravity*              :center
   ,*message-window-input-gravity*        :center
   ,*input-window-gravity*                :center
   ,*input-window-input-gravity*          :center
   ;; border style
   ,*window-border-style*                 :thin
   ;; border width
   ,*message-window-padding*              3
   ,*maxsize-border-width*                3
   ,*normal-border-width*                 3
   ,*transient-border-width*              3
   ,*float-window-border*                 2
   ,*float-window-title-height*           2)

#+end_src
*** Window Placements
#+begin_src lisp
  ;; Clearing window placement rules
  (clear-window-placement-rules)
  ;; Work
  (define-frame-preference *group-dev*
                           ;; frame raise lock (lock AND raise == jumpto)
                           (      0     t  nil    :class "Emacs")
                           (      1     t  nil    :class "Alacritty"))
  ;; Read
  (define-frame-preference *group-read*
                           (      0     t    t    :class "sioyek"))
  ;; Web
  (define-frame-preference *group-web*
                           (      0     t    t    :role "browser")
                           (      0     t    t    :class "Nyxt")
                           )
  (define-frame-preference *group-relax*
                           (      0     t    t    :title "newsboat"))
#+end_src
