#+TITLE: StumpWM Config
#+AUTHOR: Luca Andriotto
#+PROPERTY: header-args :tangle config
#+auto_tangle: t
#+DESCRIPTION: Il window manager che sto iniziando ad apprezzare.
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Table of Contents :toc:
- [[#initializations][INITIALIZATIONS]]
  - [[#variables][Variables]]
  - [[#modularity][Modularity]]
  - [[#system-helpers][System Helpers]]
  - [[#files][Files]]
  - [[#modules][Modules]]
  - [[#keymaps][Keymaps]]
  - [[#runners][Runners]]
  - [[#themes][Themes]]
- [[#appeareance][APPEAREANCE]]
  - [[#parameters][Parameters]]
  - [[#borders][Borders]]
  - [[#desktop-background][Desktop background]]
  - [[#fonts][Fonts]]
  - [[#gaps][Gaps]]
  - [[#messageinput-box][Message/Input box]]
  - [[#startup-message][Startup message]]
  - [[#which-key][Which-key]]
- [[#settings][SETTINGS]]
  - [[#messageinput-box-1][Message/Input box]]
  - [[#modeline][Modeline]]
  - [[#session][Session]]
  - [[#startup][Startup]]
  - [[#windows][Windows]]

* TODO INITIALIZATIONS
** Variables
*** Directories
#+begin_src lisp
  (in-package :stumpwm)

  (defvar al/init-directory
    (directory-namestring
     (truename (merge-pathnames
                "stumpwm" (uiop:xdg-config-pathname))))
    "A directory with initially loaded files.")

  (defvar al/modules-directory
    (directory-namestring
     (truename (merge-pathnames
                ".stumpwm.d/modules" (user-homedir-pathname))))
    "A directory with initially loaded files.")

  (defvar al/data-directory
    (directory-namestring
     (truename (merge-pathnames
                (uiop:xdg-data-pathname) "stumpwm")))
    "A directory with data files.")
#+end_src

*** Logs
#+begin_src lisp
  (redirect-all-output (merge-pathnames "log" al/data-directory))
#+end_src

** Modularity
#+begin_src lisp
  (defun al/load (filename)
    "Load a file FILENAME (without extension) from `al/init-directory'."
    (let ((file (merge-pathnames (concat filename ".lisp")
                                 al/init-directory)))
      (if (probe-file file)
          (load file)
          (format *error-output* "File '~a' doesn't exist." file))))

  (defun al/load-module (name)
    "Load contributed stumpwm module NAME.
  Return nil, if the module does not exist.
  This function is similar to `load-module' command, except it returns nil
  instead of any error."
    (let ((module (find-module (string-downcase name))))
      (and module
           (progn (asdf:operate 'asdf:load-op module)
                  t))))
#+end_src

** System Helpers
*** Battery
#+begin_src lisp
  (defparameter *battery-percent* "")

  (defun get-battery-status ()
    (let* ((batgetcap (run-shell-command "cat /sys/class/power_supply/BAT0/capacity | tr -d '\\r\\n'" t)))
      (setf *battery-percent* (format nil "^6^f1^f0^n ~a% " batgetcap))))

  (defun battery-percentage (ml)
    (declare (ignore ml))
    ,*battery-percent*)

  (run-with-timer 0 10 #'get-battery-status)
  (add-screen-mode-line-formatter #\B #'battery-percentage)
#+end_src

*** Date
Managed by =*time-modeline-string*=

*** Colon
#+begin_src lisp
  ;; prompt the user for an interactive command. The first arg is an
  ;; optional initial contents.
  (defcommand colon1 (&optional (initial "")) (:rest)
    (let ((cmd (read-one-line (current-screen) ": " :initial-input initial)))
      (when cmd
        (eval-command cmd t))))
#+end_src

*** Keybindings
#+begin_src lisp
  (defun tr-define-key (key command)
    (define-key *top-map* (kbd (concat "s-" key )) command)
    (define-key *root-map* (kbd key) command))
#+end_src

*** Search
#+begin_src lisp
;; Web jump (works for DuckDuckGo and Imdb)
(defmacro make-web-jump (name prefix)
  `(defcommand ,(intern name) (search) ((:rest ,(concatenate 'string name " search: ")))
    (nsubstitute #\+ #\Space search)
    (run-shell-command (concatenate 'string ,prefix search))))
#+end_src

*** Splitting
Focus the created frame.
#+begin_src lisp
  (defcommand al/hsplit () ()
    (hsplit)
    (move-focus :right))

  (defcommand al/vsplit () ()
    (vsplit)
    (move-focus :down))
#+end_src

*** Syncthing
#+begin_src lisp
  (defvar *syncthing-p* nil
    "Keeps track of Syncthing execution, off by default on startup")

  (defcommand start-syncthing () ()
    "Launch Syncthing if it is not already running"
    (if *syncthing-p*
        (message "Syncthing is already running")
        (progn
          (run-shell-command "syncthing --no-browser &")
          (setf *syncthing-p* t)
          (message "Launching ^6Syncthing^n..."))))

  (defcommand stop-syncthing () ()
    "Stop Syncthing"
    (stumpwm:run-shell-command "killall syncthing")
    (setf *syncthing-p* nil)
    (message "^6Syncthing^n is now stopped."))

  (defcommand toggle-syncthing () ()
    (if *syncthing-p*
        (run-commands "stop-syncthing")
        (run-commands "start-syncthing")))

  ;; modeline status

  (defun get-syncthing-status ()
    (if *syncthing-p*
        (setf *syncthing-ml-status*
              (format nil "^6^f1^f0^n "))
        (setf *syncthing-ml-status* "")))

  (defun ml-fmt-syncthing-status (ml)
    (declare (ignore ml))
    (get-syncthing-status))

  (add-screen-mode-line-formatter #\s #'ml-fmt-syncthing-status)
#+end_src

** Files
#+begin_src lisp
  (al/load "modules")
  (al/load "settings")
  (al/load "keys")
  (al/load "themes")
#+end_src

** TODO Modules
See [[file:modules.org][Modules]].

** Keymaps
Keymaps to handle modules.
See [[file:keymaps.org][Keymaps]].

** Runners
This section gathers all the program wrappers.
#+begin_src lisp
  ;; Editor
  (defcommand editor () ()
    "run emacs"
    (run-or-raise "emacsclient -c" '(:class "Emacs")))
  ;; Browsers
  (defcommand browser () ()
    "run firefox"
    (run-or-raise "firefox" '(:class "firefox")))
  (defcommand nyxt () ()
    "run nyxt"
    (run-or-raise "nyxt" '(:class "Nyxt")))
  (defcommand brave () ()
    "run brave"
    (run-or-raise "brave" '(:class "Brave")))
  ;; News
  (defcommand newsboat () ()
    "run `newsboat`"
    (run-or-raise "alacritty -T 'newsboat' -e 'newsboat'" '(:title "newsboat")))
  ;; Office
  (defcommand libreoffice () ()
    "run LibreOffice"
    (run-or-raise "libreoffice7.6" '(:class "LibreOffice")))
  ;; Engineering
  (defcommand matlab () ()
    (run-or-raise "/usr/local/MATLAB/R2023a/bin/matlab" '(:class "MATLAB")))
  ;; Study and research
  (defcommand sioyek () ()
    "run `sioyek`"
    (run-or-raise "sioyek" '(:class "sioyek")))
#+end_src

** TODO Themes
See [[file:themes.org][Themes]].

* TODO APPEAREANCE
Changing themes for the various graphical components. Fare il merge con theme fuori.
** Parameters
#+begin_src lisp
  ;; Input box
  (defparameter *msg-bg-color*     (nth 0 *colors*))
  (defparameter *msg-fg-color*     (nth 8 *colors*))
  (defparameter *msg-border-color* (nth 5 *colors*))
  ;; Mode-line
  (defparameter *mode-line-bg-color* (nth 0 *colors*))
  (defparameter *mode-line-fg-color* (nth 8 *colors*))
#+end_src

** Borders
#+begin_src lisp
  (set-focus-color         *msg-border-color*)
  (set-win-bg-color        *msg-bg-color*)
  (set-unfocus-color       *msg-bg-color*)
  (set-float-focus-color   *msg-border-color*)
  (set-float-unfocus-color *msg-bg-color*)
#+end_src

** Desktop background
Simply putting a color for a background. It is possible to tweak it differently.
#+begin_src lisp
  ;; set desktop background color
  (setf (xlib:window-background (screen-root (current-screen))) #x47456d)
#+end_src

** TODO Fonts
Muovi in Themes, mantieni l'entry creando il collegamento. Usare qualche simbolo nella modeline.
#+begin_src lisp
  (set-font (list
             (make-instance 'xft:font
                            :family "Hack"
                            :subfamily "Bold"
                            :size 13)
             (make-instance 'xft:font
                            :family "FontAwesome"
                            :subfamily "Regular"
                            :size 14)))
  (xft:cache-fonts)
#+end_src

** Gaps
Allowing gaps for better aesthetics.
#+begin_src lisp
  ;; Head gaps run along the 4 borders of the monitor(s)
  (setf swm-gaps:*head-gaps-size* 0        ;; Head gaps run along the 4 borders of the monitor(s)
        swm-gaps:*inner-gaps-size* 13      ;; Inner gaps run along all the 4 borders of a window
        swm-gaps:*outer-gaps-size* 7)      ;; Outer gaps add more padding to the outermost borders of a window (touching
  ;; the screen border)

  (swm-gaps:toggle-gaps)
#+end_src

** Message/Input box
#+begin_src lisp
  ;; message/input bar colors
  (set-bg-color     *msg-bg-color*)
  (set-fg-color     *msg-fg-color*)
  (set-border-color *msg-border-color*)
#+end_src

** Startup message
#+begin_src lisp
  ;; startup message
  (setf *startup-message* "^6    Stump Window Manager ^8has initialized!
    Press ^6Ctrl+t ? ^8for Help. ^6Never Stop Hacking!^n
              Powered with ^87 Common Lisp ")
#+end_src

** Which-key
#+begin_src lisp
  ;; (setf *key-seq-color* "^3")
  ;; (setf *which-key-format* "^5~5a -> ^n~a")
#+end_src

* SETTINGS
** Message/Input box
#+begin_src lisp
  (update-color-map (current-screen))
  ;; message timeout
  (setf *timeout-wait* 3)
#+end_src

** TODO Modeline
Sistemare pomodoro timer.

#+begin_src lisp
  (setf *mode-line-background-color*  *mode-line-bg-color* ; background
        ,*mode-line-foreground-color* *mode-line-fg-color* ; foreground
        ,*mode-line-border-color*     *mode-line-bg-color* ; border
        ,*time-modeline-string*       "^6^f1^f0^n %d %B (%A) ^6^f1^f0^n %H:%M" ; time format string
        ,*mode-line-timeout*          5                    ; timeout (mode-line refresh)
        ,*mode-line-border-width*     3                    ; border width
        ,*mode-line-pad-x*            3                    ; text padding in x
        ,*mode-line-pad-y*            3)                   ; text padding in y

  ;; Ordine di comparsa
  (setf *screen-mode-line-format*
        (list "^6[%g]^n "       ; groups
              ;; "^5%t^n "         ; notifications
              "%W"              ; windows
              "^>"              ; right align
              "%S"              ; slynk status
              "%s"              ; syncthing status
              "%B"              ; battery percentage
              "%T"
              "%d"))            ; time/date

  ;; turn on the mode line
  (if (not (head-mode-line (current-head)))
      (toggle-mode-line (current-screen) (current-head)))
#+end_src
*** Formatters
(#\A EMPTY)
(#\a EMPTY)
(#\B #<FUNCTION BATTERY-PERCENTAGE>)
(#\C EMPTY)
(#\c EMPTY)
(#\D EMPTY)
(#\d FMT-MODELINE-TIME)
(#\E STUMPWM-WEATHER::MODE-LINE-STR)
(#\e EMPTY)
(#\F EMPTY)
(#\f EMPTY)
(#\G EMPTY)
(#\g FMT-GROUP-LIST)
(#\H EMPTY)
(#\h FMT-HEAD)
(#\I #<FUNCTION WIFI::FMT-WIFI>)
(#\i EMPTY)
(#\J EMPTY)
(#\j EMPTY)
(#\K EMPTY)
(#\k EMPTY)
(#\L #<FUNCTION KBD-LAYOUTS::CURRENT-KEYBOARD-LAYOUT>)
(#\l EMPTY)
(#\M FMT-ALL-MINOR-MODES)
(#\m FMT-MINOR-MODES)
(#\N NOTIFICATIONS::NOTIFICATIONS-AS-STRING)
(#\n FMT-GROUP)
(#\O EMPTY)
(#\o EMPTY)
(#\P EMPTY)
(#\p EMPTY)
(#\Q EMPTY)
(#\q EMPTY)
(#\R EMPTY)
(#\r EMPTY)
(#\S #<FUNCTION ML-FMT-SLYNK-STATUS>)
(#\s #<FUNCTION ML-FMT-SYNCTHING-STATUS>)
(#\T ?)
(#\t TOMATO:MODELINE)
(#\U EMPTY)
(#\u FMT-URGENT-WINDOW-LIST)
(#\V EMPTY)
(#\v FMT-HEAD-WINDOW-LIST-HIDDEN-WINDOWS)
(#\W FMT-HEAD-WINDOW-LIST)
(#\w FMT-WINDOW-LIST)
(#\X EMPTY)
(#\x EMPTY)
(#\Y EMPTY)
(#\y EMPTY)
(#\Z EMPTY)
(#\z EMPTY)

** Session
#+begin_src lisp
  ;; set DESKTOP_SESSION variable
  (setf (getenv "DESKTOP_SESSION") "stumpwm")
#+end_src

** Startup
#+begin_src emacs-lisp
  (start-syncthing)
#+end_src

** Windows
*** Borders
#+begin_src lisp
  (setf 
   ;; format
   ,*window-format*                       "%m%s%20t"
   ;; gravities
   ,*message-window-gravity*              :center
   ,*message-window-input-gravity*        :center
   ,*input-window-gravity*                :center
   ,*input-window-input-gravity*          :center
   ;; border style
   ,*window-border-style*                 :thin
   ;; border width
   ,*message-window-padding*              3
   ,*maxsize-border-width*                3
   ,*normal-border-width*                 3
   ,*transient-border-width*              3
   ,*float-window-border*                 2
   ,*float-window-title-height*           2)

#+end_src
*** Window Placements
#+begin_src lisp
  ;; Clearing window placement rules
  (clear-window-placement-rules)
  ;; Work
  (define-frame-preference *group-dev*
                           ;; frame raise lock (lock AND raise == jumpto)
                           (      0     t  nil    :class "Emacs")
                           (      1     t  nil    :class "Alacritty"))
  ;; Read
  (define-frame-preference *group-read*
                           (      0     t    t    :class "sioyek"))
  ;; Web
  (define-frame-preference *group-web*
                           (      0     t    t    :role "browser")
                           (      0     t    t    :class "Nyxt")
                           )
  (define-frame-preference *group-relax*
                           (      0     t    t    :title "newsboat"))
#+end_src
